# Generated by Django 5.0.1 on 2024-02-09 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_follower_count_user_follower_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower_list',
            field=models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_list',
            field=models.ManyToManyField(null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
