# Generated by Django 5.0.1 on 2024-02-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_follower_list_alter_user_following_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_comments', to='network.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
