# Generated by Django 5.0.1 on 2024-02-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_comments_related_post_alter_posts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.posts'),
        ),
    ]
